-- Run this once in Supabase SQL Editor.

create table if not exists public.applications (
    id bigint generated by default as identity primary key,
    application_id text unique not null,
    name text not null,
    discord text not null,
    age integer not null,
    minecraft text,
    timezone text,
    hours_per_week integer not null,
    experience text not null,
    why_us text not null,
    strengths text,
    scenario text,
    position text,
    previous_staff_experience text,
    activity text,
    agreed_to_rules text,
    anything_else text,
    status text not null default 'Pending',
    admin_notes text default '',
    created_at timestamptz not null default now()
);

create index if not exists applications_status_idx
on public.applications(status);

create index if not exists applications_created_at_idx
on public.applications(created_at desc);

-- The Streamlit app uses the Supabase service key, so the database
-- can be kept private from normal visitors. Do NOT expose the service
-- key in your GitHub repository or frontend code.
